export default defineEventHandler(async (event) => {
  // 405는 try 바깥에서 처리해야 catch 블록이 500으로 변환하지 않음
  if (event.method !== 'GET') {
    setResponseStatus(event, 405);
    return { success: false, message: 'Method Not Allowed' };
  }

  try {
    // getQuery(event) > SSR 내부 fetch 시 상대 경로(호스트 없음)
    // + new URL() 파싱에 실패 > "invalid URL" 에러 발생
    // → event.node.req.url에 base URL을 추가해 직접 파싱하는 방식으로 대체
    const rawUrl = event.node.req.url ?? '';
    const { searchParams } = new URL(rawUrl, 'http://localhost');
    const isSample = searchParams.get('isSample') === 'true';

    // 관리자 레이아웃 가이드 > 샘플 GNB 메뉴 목록
    if (isSample) {
      return {
        success: true,
        data: [
          {
            id: 1,
            homepageType: 'ADMIN',
            menuName: '교육계획/분석/설계',
            parentMenuId: null,
            menuUrl: null,
            menuDepth: 1,
            menuOrder: 0,
            isActive: true,
            requireLogin: true,
            menuType: 'FOLDER',
            isNavigation: true,
            menuIcon: 'pencil',
            isDeleted: false,
            createdDate: '2025-07-14T13:00:59',
            lastModifiedDate: '2025-07-14T13:02:02',
            _children: [
              {
                id: 3,
                homepageType: 'ADMIN',
                menuName: '교육요청 관리',
                parentMenuId: 1,
                menuUrl: '/education/education-plan/education-request/regist',
                menuDepth: 2,
                menuOrder: 1,
                isActive: true,
                requireLogin: true,
                menuType: 'PAGE',
                isNavigation: true,
                menuIcon: 'pencil',
                isDeleted: false,
                createdDate: '2025-07-14T13:10:40',
                lastModifiedDate: '2025-07-17T08:54:55',
                _children: [],
              },
              {
                id: 9,
                homepageType: 'ADMIN',
                menuName: '교육기준정보설계',
                parentMenuId: 1,
                menuUrl: '/education/education-plan/ttm',
                menuDepth: 2,
                menuOrder: 0,
                isActive: true,
                requireLogin: true,
                menuType: 'PAGE',
                isNavigation: true,
                menuIcon: 'pencil',
                isDeleted: false,
                createdDate: '2025-07-14T13:10:40',
                lastModifiedDate: '2025-07-17T08:54:55',
                _children: [
                  {
                    id: 10,
                    homepageType: 'ADMIN',
                    menuName: '교육기준정보 엑셀업로드',
                    parentMenuId: 9,
                    menuUrl: '/education/education-plan/ttm/excel-upload',
                    menuDepth: 3,
                    menuOrder: 0,
                    isActive: true,
                    requireLogin: true,
                    menuType: 'PAGE',
                    isNavigation: false,
                    menuIcon: 'pencil',
                    isDeleted: false,
                    createdDate: '2025-07-14T13:10:40',
                    lastModifiedDate: '2025-07-17T08:54:55',
                    _children: [],
                  },
                ],
              },
              {
                id: 10,
                homepageType: 'ADMIN',
                menuName: '시행계획서 관리',
                parentMenuId: 1,
                menuUrl: '/education/education-plan/execution-plan',
                menuDepth: 2,
                menuOrder: 0,
                isActive: true,
                requireLogin: true,
                menuType: 'PAGE',
                isNavigation: true,
                menuIcon: 'pencil',
                isDeleted: false,
                createdDate: '2025-07-14T13:10:40',
                lastModifiedDate: '2025-07-17T08:54:55',
                _children: [],
              },
            ],
          },
          {
            id: 442,
            homepageType: 'ADMIN',
            menuName: '교육운영',
            parentMenuId: null,
            menuUrl: null,
            menuDepth: 1,
            menuOrder: 0,
            isActive: true,
            requireLogin: true,
            menuType: 'FOLDER',
            isNavigation: true,
            menuIcon: 'book-open',
            isDeleted: false,
            createdDate: '2025-07-14T13:00:59',
            lastModifiedDate: '2025-07-14T13:02:02',
            _children: [
              {
                id: 2002,
                homepageType: 'ADMIN',
                menuName: '과정개설',
                parentMenuId: 442,
                menuUrl: null,
                menuDepth: 2,
                menuOrder: 0,
                isActive: true,
                requireLogin: true,
                menuType: 'FOLDER',
                isNavigation: true,
                menuIcon: null,
                isDeleted: false,
                createdDate: '2025-07-14T13:10:40',
                lastModifiedDate: '2025-07-17T08:54:55',
                _children: [
                  {
                    id: 2110,
                    homepageType: 'ADMIN',
                    menuName: '운영과정개설관리',
                    parentMenuId: 443,
                    menuUrl:
                      '/education/operation/course-opening/opening-management',
                    menuDepth: 3,
                    menuOrder: 0,
                    isActive: true,
                    requireLogin: true,
                    menuType: 'PAGE',
                    isNavigation: true,
                    menuIcon: null,
                    isDeleted: false,
                    createdDate: '2025-07-14T13:10:40',
                    lastModifiedDate: '2025-07-17T08:54:55',
                    _children: [
                      {
                        id: 2111,
                        homepageType: 'ADMIN',
                        menuName: '운영과정개설관리 상세',
                        parentMenuId: 449,
                        menuUrl:
                          '/education/operation/course-opening/opening-management/detail/[id]',
                        menuDepth: 4,
                        menuOrder: 1,
                        isActive: true,
                        requireLogin: true,
                        menuType: 'PAGE',
                        isNavigation: true,
                        menuIcon: null,
                        isDeleted: false,
                        createdDate: '2025-07-14T13:10:40',
                        lastModifiedDate: '2025-07-17T08:54:55',
                        _children: [],
                      },
                    ],
                  },
                  {
                    id: 450,
                    homepageType: 'ADMIN',
                    menuName: '운영과정변경관리',
                    parentMenuId: 443,
                    menuUrl:
                      '/education/operation/course-opening/change-management',
                    menuDepth: 3,
                    menuOrder: 1,
                    isActive: true,
                    requireLogin: true,
                    menuType: 'PAGE',
                    isNavigation: true,
                    menuIcon: 'book-open',
                    isDeleted: false,
                    createdDate: '2025-07-14T13:10:40',
                    lastModifiedDate: '2025-07-17T08:54:55',
                    _children: [],
                  },
                  {
                    id: 452,
                    homepageType: 'ADMIN',
                    menuName: '사번변환처리',
                    parentMenuId: 443,
                    menuUrl:
                      '/education/operation/course-opening/employee-id-conversion',
                    menuDepth: 3,
                    menuOrder: 3,
                    isActive: true,
                    requireLogin: true,
                    menuType: 'PAGE',
                    isNavigation: true,
                    menuIcon: null,
                    isDeleted: false,
                    createdDate: '2025-07-14T13:10:40',
                    lastModifiedDate: '2025-07-17T08:54:55',
                    _children: [],
                  },
                ],
              },
            ],
          },
        ],
        message: '메뉴 목록을 성공적으로 조회했습니다.',
      };
    }
    const sampleMenuList = [
      {
        id: 1,
        homepageType: 'ADMIN',
        menuName: '오버레이 컴포넌트',
        parentMenuId: 1,
        menuUrl: '/lxp/guide/overlay',
        menuDepth: 2,
        menuOrder: 1,
        isActive: true,
        requireLogin: true,
        menuType: 'PAGE',
        isNavigation: true,
        menuIcon: 'folder',
        isDeleted: false,
        createdDate: '2025-07-14T13:10:40',
        lastModifiedDate: '2025-07-17T08:54:55',
        _children: [],
      },
      {
        id: 2,
        homepageType: 'ADMIN',
        menuName: '레이아웃 컴포넌트',
        parentMenuId: 1,
        menuUrl: '/lxp/guide/layout',
        menuDepth: 2,
        menuOrder: 0,
        isActive: true,
        requireLogin: true,
        menuType: 'PAGE',
        isNavigation: true,
        menuIcon: 'folder',
        isDeleted: false,
        createdDate: '2025-07-14T13:10:40',
        lastModifiedDate: '2025-07-17T08:54:55',
      },
      {
        id: 3,
        homepageType: 'ADMIN',
        menuName: '버튼 컴포넌트',
        parentMenuId: 1,
        menuUrl: '/lxp/guide/button',
        menuDepth: 2,
        menuOrder: 0,
        isActive: true,
        requireLogin: true,
        menuType: 'PAGE',
        isNavigation: true,
        menuIcon: 'folder',
        isDeleted: false,
        createdDate: '2025-07-14T13:10:40',
        lastModifiedDate: '2025-07-17T08:54:55',
      },
    ];

    return {
      success: true,
      data: sampleMenuList,
      message: '메뉴 목록을 성공적으로 조회했습니다.',
    };
  } catch (error: any) {
    console.error('메뉴 목록 조회 중 오류 발생:', error);
    // H3Error(statusCode 포함)는 그대로 throw, 그 외만 500으로 처리
    if (error?.statusCode) throw error;
    throw createError({
      statusCode: 500,
      statusMessage: 'Internal Server Error',
    });
  }
});
